<a href="https://colab.research.google.com/github/veronicaldfaria/bootcamp-data-analytics/blob/main/Python_para_Dados_Numpy_1_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr = np.array([2, 4, 6, 7, 8])
arr[1]

4

In [3]:
arr[0]

2

In [4]:
cartela_bingo = np.array([[16, 10,  3, 15],
                            [14, 23, 17, 27],
                            [ 6, 19,  3,  1],
                            [10,  4, 18, 19]])
cartela_bingo

array([[16, 10,  3, 15],
       [14, 23, 17, 27],
       [ 6, 19,  3,  1],
       [10,  4, 18, 19]])

In [5]:
cartela_bingo[:, 1].reshape((4,1))

array([[10],
       [23],
       [19],
       [ 4]])

In [6]:
cartela_bingo[0]

array([16, 10,  3, 15])

In [7]:
np.sort(cartela_bingo)

array([[ 3, 10, 15, 16],
       [14, 17, 23, 27],
       [ 1,  3,  6, 19],
       [ 4, 10, 18, 19]])

In [8]:
np.sort(cartela_bingo, axis=0)

array([[ 6,  4,  3,  1],
       [10, 10,  3, 15],
       [14, 19, 17, 19],
       [16, 23, 18, 27]])

## 1.1 Explorando Ecossistemas:
Como bióloga marinha, me encontrei em uma expedição nas profundezas do Oceano Pacífico, onde estávamos estudando a biodiversidade e a saúde dos recifes de coral. O catálogo abaixo demonstra dados das espécies encontradas, considere a seguinte ordem de colunas:

**ID da espécie, quantidade de representantes encontrados, profundeza, tamanho médio da espécie**



*  Selecione a segunda coluna com a quantidade de espécies encontradas e adicione em um array as qtd_especies.
*  De qtd_especies selecione apenas as primeiras 3 quantidades e print
*  Print as 5 últimas quantidades de espécies
*  Crie um array que contenha apenas os tamanhos das espécies e ordene por ordem crescente






In [9]:
especies = np.array([[747,  89,  33,   5],
                    [623, 123,  32,  13],
                    [501,  22,  49,   2],
                    [116, 101,  42,  10],
                    [297,  56,  69,  22],
                    [613,  64,  27,   7],
                    [295,  84,  29,  14],
                    [692, 105,  72,  16],
                    [229, 103,  35,   5],
                    [374, 124,  70,   1]])
especies

array([[747,  89,  33,   5],
       [623, 123,  32,  13],
       [501,  22,  49,   2],
       [116, 101,  42,  10],
       [297,  56,  69,  22],
       [613,  64,  27,   7],
       [295,  84,  29,  14],
       [692, 105,  72,  16],
       [229, 103,  35,   5],
       [374, 124,  70,   1]])

## Filtrando Arrays

In [10]:
arr1 = np.array([1, 2, 3, 4, 5])
mask = arr1 % 3 == 0
mask

array([False, False,  True, False, False])

In [11]:
pessoas_id_idade = np.array([[1, 22], [2, 21], [3, 27], [4, 26]])
pessoas_id_idade

array([[ 1, 22],
       [ 2, 21],
       [ 3, 27],
       [ 4, 26]])

In [12]:
cartela_bingo = np.array([[16, 10,  3, 15],
       [14, 23, 17, 27],
       [ 6, 19,  3,  1],
       [10,  4, 18, 19]])
cartela_bingo

array([[16, 10,  3, 15],
       [14, 23, 17, 27],
       [ 6, 19,  3,  1],
       [10,  4, 18, 19]])

## 1.2 Ainda usando o Array de espécies marítimas.

*   Usando um index booleano crie um array que contém os dados da maior espécie encontrada (considerando o seu tamanho), esse valor corresponde ao valor 22.

*   Usando fency index faça um array que contém apenas dados da espécie com ID 297
*   Usando np.where() faça um array com a linha com dados correspondentes a espécie com 105 representantes encontrados.
*   Considere a profundeza em que o espécie foi encontrada substitua valores maiores que 60 com "Profundo"



In [13]:
especies

array([[747,  89,  33,   5],
       [623, 123,  32,  13],
       [501,  22,  49,   2],
       [116, 101,  42,  10],
       [297,  56,  69,  22],
       [613,  64,  27,   7],
       [295,  84,  29,  14],
       [692, 105,  72,  16],
       [229, 103,  35,   5],
       [374, 124,  70,   1]])

## 1.3 Ainda no conjunto 'especies'.

* Adicione mais 2 espécies ao array: [[204, 10, 40, 12], [392, 11, 81, 11]]
* Adicione mais uma coluna na no array original agora com o número de espécies encontradas com que indica se o animal enxerga ou não: [0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0]

In [14]:
novas_especies = np.array([[204, 10, 40, 12], [392, 11, 81, 11]])

In [16]:
np.concatenate((especies, novas_especies))

array([[747,  89,  33,   5],
       [623, 123,  32,  13],
       [501,  22,  49,   2],
       [116, 101,  42,  10],
       [297,  56,  69,  22],
       [613,  64,  27,   7],
       [295,  84,  29,  14],
       [692, 105,  72,  16],
       [229, 103,  35,   5],
       [374, 124,  70,   1],
       [204,  10,  40,  12],
       [392,  11,  81,  11]])

In [18]:
especies.shape

(10, 4)

In [22]:
ver = np.array([0, 1, 0, 0, 0, 0, 1, 0, 1, 1]).reshape((10, 1))
ver

array([[0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1]])

In [23]:
np.concatenate((especies, ver), axis=1)

array([[747,  89,  33,   5,   0],
       [623, 123,  32,  13,   1],
       [501,  22,  49,   2,   0],
       [116, 101,  42,  10,   0],
       [297,  56,  69,  22,   0],
       [613,  64,  27,   7,   0],
       [295,  84,  29,  14,   1],
       [692, 105,  72,  16,   0],
       [229, 103,  35,   5,   1],
       [374, 124,  70,   1,   1]])