<a href="https://colab.research.google.com/github/veronicaldfaria/bootcamp-data-analytics/blob/main/Python_para_Dados_Numpy_1_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
acidentes = np.array([[1, 3, 2],
                    [0, 1, 0],
                    [2, 1, 4],
                    [0, 0, 0],
                    [1, 1, 0]])

In [3]:
acidentes

array([[1, 3, 2],
       [0, 1, 0],
       [2, 1, 4],
       [0, 0, 0],
       [1, 1, 0]])

### 1. O cliente que teve acidente abaixo da média nos últimos 2 anos, ganhará um desconto no seu seguro. Identifique-os.


In [6]:
ultimos_2_anos = acidentes[:, 1:]
media_acidentes = np.mean(ultimos_2_anos)
clientes_desconto = np.where(np.mean(ultimos_2_anos, axis=1) < media_acidentes)[0]
clientes_desconto

array([1, 3, 4])

### 2. Qual cliente teve pelo menos 2 anos sem cometer acidentes?

In [8]:
anos_sem_acidentes = np.sum(acidentes == 0, axis=1)
clientes_sem_acidentes = np.where(anos_sem_acidentes >= 2)[0]
clientes_sem_acidentes

array([1, 3])

### 3. Uma professora quer que seus alunos apliquem a função (3x + 2y + x*y) em um conjunto de dados. Ela dá dois arrays aos estudantes e pede que seja feita essa operação.


In [10]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([6, 7, 8, 9, 10])
resultado = 3*x + 2*y + x*y
resultado

array([21, 34, 49, 66, 85])

### 4. A mesma professora percebeu que houve um erro em todas as provas dos estudantes e esqueceu de anotar a nota de trabalhos apresentados durante o semestre. Já que foi feito em grupo ela vai adicionar a mesma nota para todos os estudantes. No array cada estudante representa uma linha e cada coluna uma prova. Adicione para cada prova de cada estudante os valores: 1, 2, 1.

In [12]:
notas_provas = np.array([[7, 8, 9],
                         [6, 7, 8],
                         [8, 9, 10],
                         [7, 6, 7],
                         [5, 6, 7]])
notas_trabalhos = np.array([1, 2, 1])
notas_finais = notas_provas + notas_trabalhos
notas_finais

array([[ 8, 10, 10],
       [ 7,  9,  9],
       [ 9, 11, 11],
       [ 8,  8,  8],
       [ 6,  8,  8]])